name: NIKO KO
favicon: null
layout_spectrum: 0.07238763011991978
typography_spectrum: 0.9676550978329033
title: Niko
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7740504578687251
  lightness: 0.3489791511092335
  saturation: 0.11511858808808029
  rhythmicContrast: 0.5708743114955723
purpose: []
