typography_spectrum: 0.60418
color:
  brandColors:
    - '#de365f'
    - '#101334'
    - '#33c3cf'
    - '#b5fef3'
    - '#fbbabb'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: NIKO KO
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: First Post
    id: 9aecddf0-3b47-497a-9686-e8f83fc5c954
    type: content
favicon: null
title: Niko
purpose: []
