name: NIKO KO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60418
title: Niko
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#de365f'
    - '#101334'
    - '#33c3cf'
    - '#b5fef3'
    - '#fbbabb'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
